import Head from 'next/head'
import { FetchPost, FetchUsers } from '@/libs/db'
import Link from 'next/link';

export default function Home({ posts, users}: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
      <Link href={'/posts'}>Posts</Link>
      <table className="table table-bordered table-responsive">
        <thead>
          <tr>
          <th className='table-info'>ID</th>
            <th className='table-success'>Title</th>
            <th className='table-dark'>Content</th>
            <th className='table-secondary'>Email</th>
          </tr>
        </thead>
        <tbody>
          {posts.map((post:Post) => (
            <tr key={post.id}>
              <td>{post.id}</td>
              <td>{post.title}</td>
              <td>{post.content}</td>
              <td>{post.email}</td>
            </tr>
          ))}
          </tbody>
        </table>
        <table className="table table-bordered table-responsive">
        <thead>
          <tr>
          <th className='table-primary'>Id</th>
            <th className='table-success'>Email</th>
            <th className='table-dark'>Password</th>
          </tr>
        </thead>
        <tbody>
          {users.map((user:User) => (
            <tr key={user.id}>
              <td>{user.id}</td>
              <td>{user.email}</td>
              <td>{user.password}</td>
            </tr>
          ))}
          </tbody>
        </table>
    </>
  )
}

export async function getServerSideProps() {
  const posts = await FetchPost();
  const users = await FetchUsers();
  return {
    props: {
      posts: JSON.parse(JSON.stringify(posts)),
      users: JSON.parse(JSON.stringify(users)),
    },
  };
}

interface Post {
  id: number;
  title: string;
  content: string;
  email: string;
}

interface User {
  id:number
  email: string
  password: string
}

interface Props {
  posts: Post[];
  users: User[];
}